title:            "沈迦勒的速记本"
description:      "沈迦勒,博客"
url:              "jerry9032.github.io"
signoff:          "沈迦勒"
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         首页
    url:          /
  - name:         存档
    url:          /archive
  - name:         标签
    url:          /tags
  - name:         关于
    url:          /about
  - name:         GitHub
    url:          http://github.com/jerry9032
    external:     true
highlighter:      true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
