title:            "沈迦勒的速记本"
description:      "沈迦勒,博客"
url:              "jerry9032.github.io"
signoff:          "沈迦勒"
disqus_shortname: "jerry-manuscript"
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         首页
    url:          /
  - name:         分类
    url:          /category
  - name:         关于
    url:          /about
# ------------ CONFIGURABLE END ------------

permalink:        /post/:title
defaults:
  - values:
      layout: "default"
